version: "3"
services:
  matchzy-discord-relay:
    build: .
    container_name: matchzy-relay
    ports:
      - "5010:80"
    environment:
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/DEIN_WEBHOOK
    volumes:
      - matchzy_uploads:/uploads

volumes:
  matchzy_uploads:
